[package]
name = "wallet-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
bitcoin = "0.32.5"
rand = "0.9.1"
rand_core = "0.9.3"
secp256k1 = {version = "0.8", features = ["rand"]}
